PROJECT = "LuatOS-SoC-Test"
VERSION = "1.0.0"
MOD_TYPE = rtos.bsp()
log.info("MOD_TYPE", MOD_TYPE)

sys = require("sys")
adcTest = require("adcTest")
cryptoTest = require("cryptoTest")
fdbTest = require("fdbTest")
i2cTest = require("i2cTest")
fsTest = require("fsTest")
gpioTest = require("gpioTest")
jsonTest = require("jsonTest")
pwmTest = require("pwmTest")
mcuTest = require("mcuTest")
pinTest = require("pinTest")
rtcTest = require("rtcTest")
rtosTest = require("rtosTest")
stringTest = require("stringTest")
zbuffTest = require("zbuffTest")
wlanTest = require("wlanTest")
socketTest = require("socketTest")
bleTest = require("bleTest")
esp32Test = require("esp32Test")
espnowTest = require("espnowTest")

if mcu then mcu.setClk(240) end

adcTest.test()
cryptoTest.test()
fdbTest.test()
i2cTest.test()
fsTest.test()
gpioTest.test()
jsonTest.test()
pwmTest.test()
mcuTest.test()
pinTest.test()
rtcTest.test()
rtosTest.test()
stringTest.test()
zbuffTest.test()
wlanTest.test()
bleTest.test()
socketTest.test()
esp32Test.test()
espnowTest.test()

sys.run()
